<?php
$parameters = array(
    // --- Database (env-driven, do not hardcode) ---
    'db_driver' => 'pdo_mysql',
    'db_host' => getenv('MAUTIC_DB_HOST') ?: file_get_contents(getenv('MAUTIC_DB_HOST_FILE')),
    'db_port' => getenv('MAUTIC_DB_PORT') ?: file_get_contents(getenv('MAUTIC_DB_PORT_FILE')),
    'db_name' => getenv('MAUTIC_DB_DATABASE') ?: file_get_contents(getenv('MAUTIC_DB_DATABASE_FILE')),
    'db_user' => getenv('MAUTIC_DB_USER') ?: file_get_contents(getenv('MAUTIC_DB_USER_FILE')),
    'db_password' => getenv('MAUTIC_DB_PASSWORD') ?: file_get_contents(getenv('MAUTIC_DB_PASSWORD_FILE')),
    'db_table_prefix' => null,
    'db_backup_tables' => 1,
    'db_backup_prefix' => 'bak_',
    'db_host_ro' => null,

    // --- Site / hosting ---
    'site_url' => 'https://mailing.smartoys.be',
    'webroot' => null,
    'image_path' => 'media/images',
    'locale' => 'en_GB',
    'default_timezone' => 'UTC',
    'trusted_proxies' => array(
        '172.16.0.0/12',
        '10.0.0.0/8',
        '192.168.0.0/16',
        '127.0.0.1',
    ),
    'trusted_hosts' => array(
        'mailing\.smartoys\.be$',
        '^localhost$',
    ),
    'dev_hosts' => array(),

    // --- Keys (PRESERVE — do not regenerate, or you lose stored encrypted secrets) ---
    'secret_key' => 'e3e8500295b811319e0e464943aeb11d001b8d085e302bf294ba9650d1643e91',
    'rememberme_key' => '58291ce57bec6d912e086285f87c07b736425b6f',
    'rememberme_lifetime' => 31536000,
    'rememberme_path' => '/',

    // --- Mailer (SMTP via smtprelay) ---
    'mailer_from_name'  => 'Smartoys mailing',
    'mailer_from_email' => 'mailing@smartoys.be',
    'mailer_return_path'=> 'mailing@smartoys.be',
    'mailer_reply_to_email' => null,
    'mailer_transport'  => 'smtp',
    'mailer_host'       => 'smtprelay',
    'mailer_port'       => '25',
    'mailer_user'       => null,
    'mailer_password'   => null,
    'mailer_encryption' => null,
    'mailer_auth_mode'  => null,
    'mailer_dsn'        => 'smtp://smtprelay:25',
    'mailer_spool_type' => 'memory',
    'mailer_spool_path' => '/var/www/html/var/spool',
    'mailer_spool_msg_limit'       => 100,
    'mailer_spool_time_limit'      => 1800,
    'mailer_spool_recover_timeout' => 1800,
    'mailer_spool_clear_timeout'   => 3600,
    'mailer_memory_msg_limit' => 100,
    'mailer_amazon_region' => 'us-east-1',
    'mailer_amazon_other_region' => null,
    'mailer_custom_headers' => array(),
    'mailer_append_tracking_pixel' => 1,
    'mailer_convert_embed_images' => 1,
    'mailer_is_owner' => 0,
    'mailer_mailjet_sandbox' => 0,
    'mailer_mailjet_sandbox_default_mail' => null,
    'mailer_address_length_limit' => 320,

    // --- Monitored mailboxes (bounces, replies, unsubscribes) ---
    'monitored_email' => array(
        'general' => array(
            'address' => 'mailing@smartoys.be',
            'host' => 'mail.smartoys.be',
            'port' => '7993',
            'encryption' => '/ssl',
            'user' => 'mailing@smartoys.be',
            'password' => 'BmxRy9pQ2fg',
            'use_attachments' => '',
        ),
        'EmailBundle_bounces'      => array('address'=>'','host'=>'','port'=>'993','encryption'=>'/ssl','user'=>'','password'=>'','override_settings'=>'0','folder'=>'INBOX'),
        'EmailBundle_unsubscribes' => array('address'=>'','host'=>'','port'=>'993','encryption'=>'/ssl','user'=>'','password'=>'','override_settings'=>'0','folder'=>'INBOX'),
        'EmailBundle_replies'      => array('address'=>'','host'=>'','port'=>'993','encryption'=>'/ssl','user'=>'','password'=>'','override_settings'=>'0','folder'=>'INBOX'),
    ),

    // --- Symfony Messenger (RabbitMQ via compose 'rabbitmq' alias) ---
    // --- Symfony Messenger (RabbitMQ via compose 'mautic-smart-rabbitmq-1' alias) ---
    'messenger_dsn_email'  => 'amqp://mautic:mautic@rabbitmq:5672/mautic/email',
    'messenger_dsn_hit'    => 'amqp://mautic:mautic@rabbitmq:5672/mautic/hit',
    'messenger_dsn_failed' => 'amqp://mautic:mautic@rabbitmq:5672/mautic/failed',
    'messenger_retry_strategy_max_retries' => 3,
    'messenger_retry_strategy_delay'       => 1000,
    'messenger_retry_strategy_multiplier'  => 2,
    'messenger_retry_strategy_max_delay'   => 0,
    'queue_mode' => 'command_process',

    // --- Cookies ---
    'cookie_path' => '/',
    'cookie_secure' => null,
    'cookie_httponly' => false,

    // --- Date / pagination ---
    'date_format_full'     => 'F j, Y g:i a T',
    'date_format_short'    => 'D, M d',
    'date_format_dateonly' => 'F j, Y',
    'date_format_timeonly' => 'g:i a',
    'default_pagelimit' => 15,
    'default_daterange_filter' => '-24 hours',
    'events_orderby_dir' => 'ASC',

    // --- IP lookup ---
    'ip_lookup_service' => 'maxmind_download',
    'ip_lookup_auth' => '36y1iqf6ZKvblYD8',
    'ip_lookup_config' => array(),
    'ip_lookup_create_organization' => 0,
    'anonymize_ip' => 0,
    'track_contact_by_ip' => 0,
    'track_by_tracking_url' => 1,
    'track_private_ip_ranges' => false,
    'do_not_track_ips' => array(),
    'do_not_track_internal_ips' => array(),
    'do_not_track_404_anonymous' => 0,
    'anonymize_ip_address_in_background' => false,

    // --- Bots (excluded from tracking) ---
    'do_not_track_bots' => array(
        'MSNBOT','msnbot-media','bingbot','Googlebot','Google Web Preview',
        'Mediapartners-Google','Baiduspider','Ezooms','YahooSeeker','Slurp',
        'AltaVista','AVSearch','Mercator','Scooter','InfoSeek','Ultraseek','Lycos',
        'Wget','YandexBot','Java/1.4.1_04','SiteBot','Exabot','AhrefsBot','MJ12bot',
        'NetSeer crawler','TurnitinBot','magpie-crawler','Nutch Crawler','CMS Crawler',
        'rogerbot','Domnutch','ssearch_bot','XoviBot','digincore','fr-crawler',
        'SeznamBot','Seznam screenshot-generator','Facebot','facebookexternalhit',
    ),

    // --- Privacy / GDPR ---
    'gdpr_user_purge_threshold' => 1095,

    // --- API ---
    'api_enabled' => 1,
    'api_enable_basic_auth' => false,
    'api_oauth2_access_token_lifetime' => 3,
    'api_oauth2_refresh_token_lifetime' => 30,
    'api_batch_max_limit' => '200',
    'api_rate_limiter_limit' => 0,
    'api_rate_limiter_cache' => array('adapter' => 'cache.adapter.filesystem'),

    // --- Uploads / paths ---
    'max_size' => '6',
    'allowed_extensions' => array(
        'csv','doc','docx','epub','gif','jpg','jpeg','mpg','mpeg','mp3',
        'odt','odp','ods','pdf','png','ppt','pptx','tif','tiff','txt','xls','xlsx','wav',
    ),
    'allowed_mimetypes' => array(
        'csv'=>'text/csv','doc'=>'application/msword',
        'docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'epub'=>'application/epub+zip','gif'=>'image/gif','jpg'=>'image/jpeg','jpeg'=>'image/jpeg',
        'mpg'=>'video/mpeg','mpeg'=>'video/mpeg','mp3'=>'audio/mpeg',
        'odt'=>'application/vnd.oasis.opendocument.text','odp'=>'application/vnd.oasis.opendocument.presentation',
        'ods'=>'application/vnd.oasis.opendocument.spreadsheet','pdf'=>'application/pdf','png'=>'image/png',
        'ppt'=>'application/vnd.ms-powerpoint',
        'pptx'=>'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'tif'=>'image/tiff','tiff'=>'image/tiff','txt'=>'text/plain',
        'xls'=>'application/vnd.ms-excel',
        'xlsx'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','wav'=>'audio/wav',
    ),
    'blacklisted_extensions' => array('php','sh'),
    'streamed_extensions' => array('gif','jpg','jpeg','mpg','mpeg','mp3','pdf','png','wav'),
    'cache_path'  => '/var/www/html/var/cache',
    'log_path'    => '/var/www/html/var/logs',
    'media_path'  => 'media',
    'tmp_path'    => '/var/www/html/var/tmp',
    'upload_dir'  => '/var/www/html/docroot/media/files',
    'form_upload_dir'    => '/var/www/html/docroot/media/files/form',
    'report_temp_dir'    => '/var/www/html/docroot/media/files/temp',
    'contact_export_dir' => '/var/www/html/docroot/media/files/temp',
    'import_leads_dir'   => '/var/www/html/var/import',

    // --- Theme ---
    'theme' => 'Theme1212Column',
    'theme_email_default' => 'blank',
    'theme_import_allowed_extensions' => array('json','twig','css','js','htm','html','txt','jpg','jpeg','png','gif'),

    // --- Contact / segment / campaign ---
    'contact_columns' => array('name','email','location','stage','points','last_active','id'),
    'contact_unique_identifiers_operator' => 'OR',
    'company_unique_identifiers_operator' => 'OR',
    'contact_allow_multiple_companies' => 1,
    'contact_api_count_cache_ttl' => 5,
    'contact_export_in_background' => 1,
    'contact_export_batch_size' => 20000,
    'create_custom_field_in_background' => false,
    'segment_rebuild_time_warning' => 30,
    'segment_build_time_warning' => 30,
    'campaign_time_wait_on_event_false' => 'PT1H',
    'campaign_use_summary' => 0,
    'campaign_by_range' => 0,
    'campaign_send_notification_to_author' => 1,
    'campaign_notification_email_addresses' => null,
    'delete_campaign_event_log_in_background' => false,
    'parallel_import_limit' => '1',
    'background_import_if_more_rows_than' => 0,
    'cat_in_page_url' => 0,
    'cached_data_timeout' => 30,
    'batch_sleep_time' => '1',
    'batch_campaign_sleep_time' => false,
    'transliterate_page_title' => 0,

    // --- Email defaults ---
    'unsubscribe_text' => '<a href="|URL|">Unsubscribe</a> to no longer receive emails from us.',
    'webview_text'     => '<a href="|URL|">Having trouble reading this email? Click here.</a>',
    'unsubscribe_message' => 'We are sorry to see you go! |EMAIL| will no longer receive emails from us. If this was by mistake, <a href="|URL|">click here to re-subscribe</a>.',
    'resubscribe_message' => '|EMAIL| has been re-subscribed. If this was by mistake, <a href="|URL|">click here to unsubscribe</a>.',
    'default_signature_text' => 'Best regards, |FROM_NAME|',
    'email_frequency_number' => 3,
    'email_frequency_time' => 'WEEK',
    'email_draft_enabled' => 0,
    'minify_email_html' => 0,
    'disable_trackable_urls' => 0,

    // --- Contact preferences (UI toggles) ---
    'show_contact_preferences' => 0,
    'show_contact_frequency' => 0,
    'show_contact_pause_dates' => 0,
    'show_contact_preferred_channels' => 0,
    'show_contact_categories' => 0,
    'show_contact_segments' => 0,

    // --- CORS ---
    'cors_restrict_domains' => 0,
    'cors_valid_domains' => array('https://www.smartoys.be'),

    // --- Webhooks ---
    'webhook_limit' => '10',
    'webhook_log_max' => '1000',
    'webhook_disable_limit' => '100',
    'webhook_timeout' => '15',
    'webhook_time_limit' => 600,
    'webhook_send_notification_to_author' => 1,
    'webhook_notification_email_addresses' => null,
    'webhook_email_details' => 1,
    'clean_webhook_logs_in_background' => false,

    // --- Reports ---
    'report_export_batch_size' => '1000',
    'report_export_max_filesize_in_bytes' => '5000000',
    'csv_always_enclose' => 1,

    // --- SMS / push (disabled) ---
    'sms_enabled' => false,
    'sms_username' => null,
    'sms_password' => null,
    'sms_sending_phone_number' => null,
    'sms_frequency_number' => null,
    'sms_frequency_time' => null,
    'sms_transport' => 'mautic.sms.twilio.transport',
    'sms_messaging_service_sid' => null,
    'sms_disable_trackable_urls' => 0,
    'notification_enabled' => false,
    'notification_landing_page_enabled' => true,
    'notification_tracking_page_enabled' => false,
    'notification_app_id' => null,
    'notification_rest_api_key' => null,
    'notification_safari_web_id' => null,
    'gcm_sender_id' => '482941778795',
    'notification_subdomain_name' => null,
    'welcomenotification_enabled' => true,

    // --- Tracking pixels (third-party) ---
    'google_analytics' => null,
    'google_analytics_id' => null,
    'google_analytics_trackingpage_enabled' => 0,
    'google_analytics_landingpage_enabled' => 0,
    'google_analytics_anonymize_ip' => 0,
    'facebook_pixel_id' => null,
    'facebook_pixel_trackingpage_enabled' => 0,
    'facebook_pixel_landingpage_enabled' => 0,

    // --- SAML SSO ---
    'saml_idp_entity_id' => 'https://mailing.smartoys.be',
    'saml_idp_own_password' => null,
    'saml_idp_email_attribute' => 'EmailAddress',
    'saml_idp_username_attribute' => null,
    'saml_idp_firstname_attribute' => 'FirstName',
    'saml_idp_lastname_attribute' => 'LastName',
    'saml_idp_default_role' => null,

    // --- Misc / advanced ---
    'twitter_handle_field' => 'twitter',
    'link_shortener_url' => null,
    'shortener_service' => null,
    'shortener_email_enable' => null,
    'shortener_sms_enable' => null,
    'do_not_submit_emails' => array(),
    'update_stability' => 'rc',
    'composer_updates' => 0,
    'translations_list_url'  => 'https://language-packs.mautic.com/manifest.json',
    'translations_fetch_url' => 'https://language-packs.mautic.com/',
    'system_update_url' => 'https://api.github.com/repos/mautic/mautic/releases',
    'stats_update_url'  => 'https://updates.mautic.org/stats/send',
    'rss_notification_url' => 'https://mautic.com/?feed=rss2&tag=notification',
    '404_page' => null,
    'max_log_files' => 7,
    'log_file_name' => 'mautic_prod.php',
    'max_entity_lock_time' => 0,
    'last_shown_tab' => null,
    'redis_primary_only' => false,
    'headers_sts' => 0,
    'headers_sts_expire_time' => 60,
    'headers_sts_subdomains' => 0,
    'headers_sts_preload' => 0,
    'load_froala_assets' => 1,
    'form_results_data_sources' => 0,
    'successful_submit_action' => 'top',
    'peak_interaction_timer_cache_timeout' => 43800,
    'peak_interaction_timer_best_default_hour_start' => 9,
    'peak_interaction_timer_best_default_hour_end' => 12,
    'peak_interaction_timer_best_default_days' => array('1','2','4'),
    'peak_interaction_timer_fetch_interactions_from' => '-60 days',
    'peak_interaction_timer_fetch_limit' => 50,
    'peak_interaction_timer_max_optimal_days' => 3,

    // --- Editor fonts ---
    'editor_fonts' => array(
        array('name'=>'Arial','font'=>'Arial, Helvetica Neue, Helvetica, sans-serif'),
        array('name'=>'Bitter','font'=>'Bitter, Georgia, Times, Times New Roman, serif','url'=>'https://fonts.googleapis.com/css?family=Bitter'),
        array('name'=>'Courier New','font'=>'Courier New, Courier, Lucida Sans Typewriter, Lucida Typewriter, monospace'),
        array('name'=>'Droid Serif','font'=>'Droid Serif, Georgia, Times, Times New Roman, serif','url'=>'https://fonts.googleapis.com/css?family=Droid+Serif'),
        array('name'=>'Georgia','font'=>'Georgia, Times, Times New Roman, serif'),
        array('name'=>'Helvetica','font'=>'Helvetica Neue, Helvetica, Arial, sans-serif'),
        array('name'=>'Lato','font'=>'Lato, Tahoma, Verdana, Segoe, sans-serif','url'=>'https://fonts.googleapis.com/css?family=Lato'),
        array('name'=>'Lucida Sans Unicode','font'=>'Lucida Sans Unicode, Lucida Grande, Lucida Sans, Geneva, Verdana, sans-serif'),
        array('name'=>'Montserrat','font'=>'Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif','url'=>'https://fonts.googleapis.com/css?family=Montserrat'),
        array('name'=>'Open Sans','font'=>'Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif','url'=>'https://fonts.googleapis.com/css?family=Open+Sans'),
        array('name'=>'Roboto','font'=>'Roboto, Tahoma, Verdana, Segoe, sans-serif','url'=>'https://fonts.googleapis.com/css?family=Roboto'),
        array('name'=>'Source Sans Pro','font'=>'Source Sans Pro, Tahoma, Verdana, Segoe, sans-serif','url'=>'https://fonts.googleapis.com/css?family=Source+Sans+Pro'),
        array('name'=>'Tahoma','font'=>'Tahoma, Geneva, Segoe, sans-serif'),
        array('name'=>'Times New Roman','font'=>'TimesNewRoman, Times New Roman, Times, Beskerville, Georgia, serif'),
        array('name'=>'Trebuchet MS','font'=>'Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif'),
        array('name'=>'Ubuntu','font'=>'Ubuntu, Tahoma, Verdana, Segoe, sans-serif','url'=>'https://fonts.googleapis.com/css?family=Ubuntu'),
        array('name'=>'Verdana','font'=>'Verdana, Geneva, sans-serif'),
        array('name'=>'ヒラギノ角ゴ Pro W3','font'=>'ヒラギノ角ゴ Pro W3, Hiragino Kaku Gothic Pro,Osaka, メイリオ, Meiryo, ＭＳ Ｐゴシック, MS PGothic, sans-serif'),
        array('name'=>'メイリオ','font'=>'メイリオ, Meiryo, ＭＳ Ｐゴシック, MS PGothic, ヒラギノ角ゴ Pro W3, Hiragino Kaku Gothic Pro,Osaka, sans-serif'),
    ),
);
